### ISSUE TITLE
Build in a conversion event for email captures 

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#10]
Are you guys able to build in a conversion event for email captures to Mailchimp if I give login access?

**Comment by laurengerardi** [comment]
Hi guys - just wanted to check in on this question.

**Comment by aldidas** [comment]
Is this related to the Sign Up Form that placed inside the footer section?

**Comment by laurengerardi** [comment]
Yes for this
<img width="556" alt="Screen Shot 2020-02-25 at 11 32 48 PM" src="https://user-images.githubusercontent.com/57407119/75312184-2a028b00-5827-11ea-9f42-4ed80be0e6a7.png">

**Comment by aldidas** [comment]
OK @laurengerardi , you can share the Mailchimp login information with us.

**Comment by laurengerardi** [comment]
trying to get in and the 2 factor is on- may have to wait until tomorrow.

**Comment by laurengerardi** [comment]
<img width="433" alt="Screen Shot 2020-02-26 at 12 24 03 AM" src="https://user-images.githubusercontent.com/57407119/75314661-684f7880-582e-11ea-90c0-99e01fb89cce.png">

**Comment by laurengerardi** [comment]
Let me know when you need the email authenticator code

**Comment by laurengerardi** [comment]
f56509207afc3fe1f67e24839aff123b33d98a3c7c875469a680459103ce09d8-1582694653

**Comment by aldidas** [comment]
OK the Verification Code works, thanks.

**Comment by aldidas** [comment]
All email submitted through sign up form now will be saved into Mailchimp Audience list.

Please check https://liveresin.ubicilembu.com
