### ISSUE TITLE
Update Copy

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#11]
Per email from @laurengerardi there is update for website copy

Document can be found here :
https://www.dropbox.com/sh/kzt6mhqooyofwha/AAB6254xpT6BHUYCRhsZDBb6a?dl=0&preview=LRP+Website+Copy+Deck.docx
- Updates noted in red
- Still waiting on the FAQs update

**Comment by aldidas** [comment]
Updated : https://liveresin.ubicilembu.com/
