### ISSUE TITLE
Homepage - Red Congolese Section

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#12]
- The margin between Red Congolese and Gold Seal SF is a little too far. 
- The Gold Seal SF should be vertical center to the logo on the left, also the font size of Gold Seal SF need to be bigger 

![Screen Shot 2020-02-25 at 12 11 54](https://user-images.githubusercontent.com/27019705/75220240-820ea280-57d1-11ea-9788-d26e0376eedf.png)

-----

**Comment by aldidas** [comment]
Updated : 
- https://liveresin.ubicilembu.com
- https://liveresin.ubicilembu.com/products/
