### ISSUE TITLE
Homepage - Meet Our Team Video Plays Does Not Have Sound

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#13]
When playing video on our team section, it does not have sound

![Screen Shot 2020-02-25 at 12 12 29](https://user-images.githubusercontent.com/27019705/75220594-5c35cd80-57d2-11ea-8f22-aadf00626b26.png)

**Comment by aldidas** [comment]
Updated here : 
- https://liveresin.ubicilembu.com/
- https://liveresin.ubicilembu.com/our-story
