### ISSUE TITLE
Footer Section

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#14]
- The copy text below Get Notified is not the same as in figma
- Hint text color on signup form is different

![Screen Shot 2020-02-25 at 12 13 05](https://user-images.githubusercontent.com/27019705/75220825-ef6f0300-57d2-11ea-9485-3f339044c083.png)

**Comment by aldidas** [comment]
Updated  please check.

**Comment by dickyabd** [comment]
updated but not using the same text as in figma yet

**Comment by aldidas** [comment]
Updated please check
