### ISSUE TITLE
Sticky Nav - Do not need to show the label

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#15]
According to figma spec, do not show the lable text for sticky nav. Applies for mobile view as well

![Screen Shot 2020-02-25 at 13 18 34](https://user-images.githubusercontent.com/27019705/75221379-43c6b280-57d4-11ea-8fce-2f6089868e92.png)

**Comment by aldidas** [comment]
Updated here : https://liveresin.ubicilembu.com/products/
