### ISSUE TITLE
Our Story

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#17]
- Need more padding between main nav to the Our Story Title
- Our Story title font size looks bigger

![Screen Shot 2020-02-25 at 13 53 45](https://user-images.githubusercontent.com/27019705/75222274-6bb71580-57d6-11ea-9b6b-e60f997b4e1d.png)

**Comment by aldidas** [comment]
Updated here : https://liveresin.ubicilembu.com/our-story/

**Comment by laurengerardi** [comment]
Is the link ready to go to the client or are you still QA'ing today?
