### ISSUE TITLE
Our Story - Kind Bill Photo Position

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#18]
The position of Kind Bill photo in demo web is lower than in the figma spec 

![Screen Shot 2020-02-25 at 13 58 18](https://user-images.githubusercontent.com/27019705/75222488-eaac4e00-57d6-11ea-8a39-40a733488f55.png)

**Comment by aldidas** [comment]
Updated : https://liveresin.ubicilembu.com/our-story/

Please check
