### ISSUE TITLE
Notes on Overall Design 

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#2]
They want to build in the store locator later so we need to hide that. 

For "News" we will have to hide that on the nav bar for now.

Designers will be updating the design flats to have the user enter their state when they are passing through the age gate. He said they should be updating it in Figma soon.

**Comment by laurengerardi** [comment]
This is the example of the Age Gate they are going to swap it to:
https://cms.tweedus.com/

**Comment by aldidas** [comment]
Hi @laurengerardi, can I get all Fonts that used by this project?

Thanks.
