### ISSUE TITLE
Store Locator - Remove the copy text on the right

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#21]
- In figma we do not have the copy on the right next to Store Locator Title.
- Make the Store Locator title as 1 line

![Screen Shot 2020-02-25 at 14 05 29](https://user-images.githubusercontent.com/27019705/75223151-6bb81500-57d8-11ea-8445-2620a43e291d.png)

in figma :
![Screen Shot 2020-02-25 at 14 10 42](https://user-images.githubusercontent.com/27019705/75223257-a326c180-57d8-11ea-9860-5993c9c7acbb.png)

**Comment by aldidas** [comment]
Updated
