### ISSUE TITLE
Mobile View - iPhone 6 Safari

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#22]
Age Gate 
- Text copy padding is not displaying correctly
- Buttons cut off

![WhatsApp Image 2020-02-25 at 14 20 00](https://user-images.githubusercontent.com/27019705/75224405-044f9480-57db-11ea-9540-92c7e1758ee8.jpeg)

![WhatsApp Image 2020-02-25 at 14 19 59](https://user-images.githubusercontent.com/27019705/75224428-0e719300-57db-11ea-8b24-00c998832d21.jpeg)

-----

Home Page
- Noticed Learn More button background color is slight different
- Recent Drop text is too small
- Skywalker OG text not displaying correctly

![WhatsApp Image 2020-02-25 at 14 33 13](https://user-images.githubusercontent.com/27019705/75225039-5513bd00-57dc-11ea-9c96-f59d286a5797.jpeg)

- Signature image is too big

![WhatsApp Image 2020-02-25 at 14 40 19](https://user-images.githubusercontent.com/27019705/75225359-0a467500-57dd-11ea-8f95-2fbe5b8fd86d.jpeg)

-----

Footer
- Padding top for Get Notified is too far
- Input email form should be not rounded corner
- Privace & Terms should not using bold font

![WhatsApp Image 2020-02-25 at 14 40 20](https://user-images.githubusercontent.com/27019705/75225370-0fa3bf80-57dd-11ea-92a1-deb6b35bb30e.jpeg)

**Comment by dickyabd** [comment]
Products 
- Need to reduce the size of Headline text, a little bigger than in figma

![WhatsApp Image 2020-02-25 at 14 58 52](https://user-images.githubusercontent.com/27019705/75226728-6e6a3880-57df-11ea-98ce-5f1b08f25cfd.jpeg)

- Popular Strain text size too big

![WhatsApp Image 2020-02-25 at 14 58 54](https://user-images.githubusercontent.com/27019705/75226816-9194e800-57df-11ea-9488-42b114dd6c35.jpeg)

- Collaboration text bottom padding too far

![WhatsApp Image 2020-02-25 at 14 58 54 (1)](https://user-images.githubusercontent.com/27019705/75226869-b0937a00-57df-11ea-93e6-6a29cf208b17.jpeg)

- Red Congolese margin with Gold Seal SF is too far
- Need to fix paragraph break line or need to decrease the font size by 1pt
- Emerald Cup Winner badge looks bigger than in figma

![WhatsApp Image 2020-02-25 at 14 58 55](https://user-images.githubusercontent.com/27019705/75227128-331c3980-57e0-11ea-8ad7-4729f08ef217.jpeg)

- Break line for "Find Live Resin Near You" is not correct and the bottom padding is too far
- Bottom padding for the address is too far

**Comment by dickyabd** [comment]
Our Process 
- Description padding is not correct

![WhatsApp Image 2020-02-25 at 15 13 18](https://user-images.githubusercontent.com/27019705/75227900-a5d9e480-57e1-11ea-8d68-a62e7d558c42.jpeg)

- Images gets cut off
- Image and Text out of bounds

![WhatsApp Image 2020-02-25 at 15 13 17](https://user-images.githubusercontent.com/27019705/75227968-ce61de80-57e1-11ea-8c85-8e9878c86f48.jpeg)

![WhatsApp Image 2020-02-25 at 15 13 17](https://user-images.githubusercontent.com/27019705/75228018-e3d70880-57e1-11ea-9cb9-2ff0e6cbf061.jpeg)

- Signature too big

![WhatsApp Image 2020-02-25 at 15 13 16](https://user-images.githubusercontent.com/27019705/75228040-ed607080-57e1-11ea-8b24-fd9caeef65b0.jpeg)

**Comment by dickyabd** [comment]
Our Story

- Padding issues

![WhatsApp Image 2020-02-25 at 15 20 45](https://user-images.githubusercontent.com/27019705/75228368-9a3aed80-57e2-11ea-9750-838e77c734e9.jpeg)

![WhatsApp Image 2020-02-25 at 15 20 46](https://user-images.githubusercontent.com/27019705/75228379-9f983800-57e2-11ea-8a4f-07666c9cf219.jpeg)

- Signature too big

![WhatsApp Image 2020-02-25 at 15 20 46 (1)](https://user-images.githubusercontent.com/27019705/75228392-a45cec00-57e2-11ea-934a-ebfe219caca3.jpeg)

**Comment by dickyabd** [comment]
FAQs

- Padding too far
- Q title is not left aligned correctly
- Plus icon not tap-able

![WhatsApp Image 2020-02-25 at 15 26 03](https://user-images.githubusercontent.com/27019705/75228751-3664f480-57e3-11ea-842f-6289172cbb10.jpeg)

**Comment by dickyabd** [comment]
Store Locator 

- Padding / margin too far

![WhatsApp Image 2020-02-25 at 15 28 07](https://user-images.githubusercontent.com/27019705/75228933-893eac00-57e3-11ea-9b51-92bfb56e65dc.jpeg)

**Comment by aldidas** [comment]
Updated, please check https://liveresin.ubicilembu.com
