### ISSUE TITLE
Mobile View - Main Menu Navigation

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#23]
- Location's bottom padding too far
- Privacy & Terms getting cut off
- Not able to scroll in small device, when trying to scroll it will scroll the main page not the menu

![WhatsApp Image 2020-02-25 at 14 53 35](https://user-images.githubusercontent.com/27019705/75226243-a6bd4700-57de-11ea-97a6-c81ef5b41d75.jpeg)

![WhatsApp Image 2020-02-25 at 14 53 22](https://user-images.githubusercontent.com/27019705/75226268-b046af00-57de-11ea-9a1a-23fafcd54212.jpeg)

**Comment by aldidas** [comment]
Updated, please check https://liveresin.ubicilembu.com
