### ISSUE TITLE
Lauren QA - Desktop

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#26]
Homepage:
Should the arrow on Red Cogolese drop down to the box at the bottom?
<img width="817" alt="Screen Shot 2020-02-26 at 12 04 38 PM" src="https://user-images.githubusercontent.com/57407119/75368793-42f35680-5890-11ea-999c-e1e4e6d9d634.png">

**Comment by laurengerardi** [comment]
Homepage Friends of the Product Logos.

Can we open a new window and click to their pages?
Gold Seal - http://www.goldsealsf.com/
Cookies - https://www.cookiesmelrose.com/
Sherbinskins - https://www.sherbinskis.com/

**Comment by laurengerardi** [comment]
Homepage: Our Team

When you click the button it goes to Our Story, it's just a weird user experience. I can call out to them.  It should say "Our Story" :)
<img width="1051" alt="Screen Shot 2020-02-26 at 12 11 56 PM" src="https://user-images.githubusercontent.com/57407119/75369404-5fdc5980-5891-11ea-9d2d-385a573e9f1d.png">

**Comment by laurengerardi** [comment]
Products Page: 
Do we need a new sugar icon? This one looks very low res compared to the others.
<img width="1113" alt="Screen Shot 2020-02-26 at 12 13 39 PM" src="https://user-images.githubusercontent.com/57407119/75369465-7b476480-5891-11ea-960d-874c909c7ea5.png">

**Comment by laurengerardi** [comment]
Our Products:
Sometimes (not all the time) when I click the name at the top, i.e. Sugar it brings you down to the Sugar box on the page, but cuts off the title. Sometimes It shows the title, can we just check this? I'm guessing it should show the title each time. It looks cleaner.
<img width="1138" alt="Screen Shot 2020-02-26 at 12 14 36 PM" src="https://user-images.githubusercontent.com/57407119/75369574-b6e22e80-5891-11ea-9114-8d73ab121ded.png">
<img width="1123" alt="Screen Shot 2020-02-26 at 12 14 45 PM" src="https://user-images.githubusercontent.com/57407119/75369576-b8135b80-5891-11ea-9d12-41163f7d82de.png">

**Comment by laurengerardi** [comment]
I will follow up with them about the copy on the two unfinished locations at the bottom of the page.
<img width="1150" alt="Screen Shot 2020-02-26 at 12 16 55 PM" src="https://user-images.githubusercontent.com/57407119/75369700-ef820800-5891-11ea-9e43-67ecaea6846a.png">

**Comment by laurengerardi** [comment]
Our Story page:

Logos at the bottom currently click out to the "Our Story page" have them click to their pages.
<img width="1139" alt="Screen Shot 2020-02-26 at 12 18 58 PM" src="https://user-images.githubusercontent.com/57407119/75369843-2eb05900-5892-11ea-81d0-0edb6da1860e.png">

Gold Seal - http://www.goldsealsf.com/
Cookies - https://www.cookiesmelrose.com/
Sherbinskins - https://www.sherbinskis.com/

**Comment by aldidas** [comment]
All issues mentioned on comments above already added / fixed, please check on the demo website.
