### ISSUE TITLE
Lauren QA - Mobile

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#27]
Our Products Page Mobile
Can we check the text over the image, looks bad. IPhone 8 +

![Text over image](https://user-images.githubusercontent.com/57407119/75369954-5f908e00-5892-11ea-82c7-16d5586589e3.jpg)

**Comment by laurengerardi** [comment]
The "Friends" Logos on both pages took awhile to load then were blurry. Not sure why. 

![Friends Logos mobile](https://user-images.githubusercontent.com/57407119/75370063-8b137880-5892-11ea-86b8-be9ad1dcaa33.jpg)

**Comment by laurengerardi** [comment]
Our Products:

When I was scrolling down, the page was blinking and showing this screen and what you are meant to see. Not sure if we can just double check this. I can try to take a video later if needed. 

![Scrolling](https://user-images.githubusercontent.com/57407119/75370124-a2526600-5892-11ea-9f20-741ae60a6277.jpg)

**Comment by aldidas** [comment]
All issues mentioned on comments above already added / fixed, please check on the demo website.
