### ISSUE TITLE
Store Locator Substitute 

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#3]
Currently, in place of the Store Locator they want to have hyper links to google map locations.

**Comment by laurengerardi** [comment]
Currently, since they only have this one location listed. 
<img width="1267" alt="Screen Shot 2020-02-26 at 11 58 46 AM" src="https://user-images.githubusercontent.com/57407119/75369081-b85f2700-5890-11ea-86de-a4918b40e3d7.png">

Can we open a new window to the Google Maps address? 
https://goo.gl/maps/KsWudKUP9LTSgXmd7

**Comment by aldidas** [comment]
The link already updated with the google map link. Please check.
