### ISSUE TITLE
 QA from Design Team - Feedback Overall

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#33]
Details: https://airtable.com/shr5dBxld1AMrQSk8
<img width="1314" alt="Screen Shot 2020-02-28 at 2 58 08 PM" src="https://user-images.githubusercontent.com/57407119/75583131-0879ed00-5a3b-11ea-8454-95a95b950181.png">
*I asked about #11 Store Locator because they told us to hide that originally. 
<img width="1312" alt="Screen Shot 2020-02-28 at 3 01 21 PM" src="https://user-images.githubusercontent.com/57407119/75583280-3b23e580-5a3b-11ea-99e2-199e535e7316.png">

**Comment by dickyabd** [comment]
@laurengerardi 

to confirm, so we should hide the store locator in the next update?

also regarding feedback number 6, they said video cropped and positioned wierd, can you clarify? we do not know how it should look like.

**Comment by dickyabd** [comment]
Can you clarify number 12, because we follow the design system in the figma spec for cta button
