### ISSUE TITLE
Mobile View - Video

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#39]
Video is cropped and positioned weird

**Comment by dickyabd** [comment]
@laurengerardi can you clarify how it should look like?

**Comment by laurengerardi** [comment]
Confirming what this will look like.

**Comment by laurengerardi** [comment]
Please, center the guy across all mobile browsers.

He should be centered and should align with the bottom of the container so that his torso is not cut off.

**Comment by aldidas** [comment]
I have updated the video layout for the mobile view. But still not sure if it's a correct layout that the client want. 

Btw if the client provide the updated figma for the mobile video section, that would be great.

**Comment by laurengerardi** [comment]
Hi just checked. They just want it so that you can see his whole body 
![Screen Shot 2020-03-04 at 12 29 20 PM](https://user-images.githubusercontent.com/57407119/75905945-cc1c0780-5e13-11ea-8743-2156b492721a.png)

**Comment by laurengerardi** [comment]
But make sure the white play button is in the center.

**Comment by dickyabd** [comment]
Still not really sure about this, let us know if this still not correct. We centered the guy and not cut off :

![thevideoguy](https://user-images.githubusercontent.com/27019705/75990215-248ff980-5f27-11ea-908e-1709e9e2e457.jpeg)

**Comment by laurengerardi** [comment]
Can you please replace the image of Ry with this one for homepage & Story ?

https://www.dropbox.com/s/kdynbue1bh33t26/LRP_Ry-Video-Still.png?dl=0

**Comment by aldidas** [comment]
The images are replaced. Please check : [here](https://liveresin.ubicilembu.com) and [here](https://liveresin.ubicilembu.com/our-story/)

**Comment by laurengerardi** [comment]
great
