### ISSUE TITLE
Store Locator

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#44]
Store Locator nav header is missing

-----

there is a note :

> _Andy had told us to hide this since it was only 1 store and not true Store Locator yet. Please let us know if you want it shown now._ 

@laurengerardi can you clarify?

**Comment by laurengerardi** [comment]
Confirming!

**Comment by dickyabd** [comment]
Hi @laurengerardi it's updated, but i'm not sure about how we put the Area name (Los Angeles, Oakland, etc). We don't have the UI spec for that.

**Comment by laurengerardi** [comment]
Following up on how this should be done.

**Comment by laurengerardi** [comment]
Leave as a list of cities for now.
