### ISSUE TITLE
CTA Buttons - UX Feedback

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#45]
I like the hover effect on CTA buttons but it bit too jarring so maybe it doesn't scale down as much so it's more subtle.

@laurengerardi we follow what is in the design system figma spec, can you clarify this?

**Comment by laurengerardi** [comment]
Confirming

**Comment by laurengerardi** [comment]
From Agency - Yes, but now that we can see it in practice, we are wondering if we can reduce the scaling animation. Will update the specs in Figma.
https://www.figma.com/file/rvIOzd70rgJyGjqfJXLkfh/Live-Resin-Project-Site-Development?node-id=2702%3A9861

**Comment by aldidas** [comment]
Updated...
