### ISSUE TITLE
Products - Mobile View - Indicator

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#51]
Similar problem as desktop: format indicator changes halfway through a section. The indicator allows user to scroll back to the top of the previous section while indicating you're still on the next section.

**Comment by dickyabd** [comment]
![image](https://user-images.githubusercontent.com/27019705/75746232-3cf7ec80-5d4c-11ea-900d-c0bc1eaca631.png)

**Comment by aldidas** [comment]
Updated...

**Comment by laurengerardi** [comment]
Hi is this updated?

**Comment by dickyabd** [comment]
please check
