### ISSUE TITLE
Products - Wrong Format Indicator

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#55]
Coloured indicator on formats section indicates the wrong format. It happens halfway through the section on a medium browser window, and right at the top of the section on a large browser browser window.

![format1](https://user-images.githubusercontent.com/27019705/75746602-5d747680-5d4d-11ea-820e-77a0d66ee1cc.png)

![format2](https://user-images.githubusercontent.com/27019705/75746605-5f3e3a00-5d4d-11ea-8102-9c43a6acd3f8.png)

**Comment by aldidas** [comment]
Updated...

**Comment by laurengerardi** [comment]
can we test tomorrow?

**Comment by dickyabd** [comment]
please check
