### ISSUE TITLE
LR Fonts 

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#6]
For the Attribute Mono font – this is an Adobe font, so you’ll need to use your Adobe license to create a web project for that one.

 
https://www.dropbox.com/sh/ayp6uprcjzccsd1/AABqwcdOf-FDFFBkMnTNK5qOa?dl=0

**Comment by aldidas** [comment]
Hi @laurengerardi I'm not subscribed to any Adobe Creative Cloud services, and it seems all required fonts only can be used by subscribed users. So I couldn't get the required fonts for this project. 

Can I get the final typekit link for the font resource?

Thanks

**Comment by laurengerardi** [comment]
Hi- let me ask now.

**Comment by laurengerardi** [comment]
Before I ask, they sent the license in the dropbox - can we use this?

https://www.dropbox.com/sh/727hkb5f3bnslyh/AAAKnqaJpOXEs6FLZaZ_8xcaa/Mont%20Family/Licenses?dl=0&subfolder_nav_tracking=1

Or download this? https://www.dropbox.com/sh/727hkb5f3bnslyh/AACj6-9DUZ1StwnQ_83VDj38a?dl=0&file_subpath=%2FMont+Family&preview=Mont+Family.zip

**Comment by aldidas** [comment]
That's the license for the Mont font. I've already downloaded & used that font and everything is fine. 

But there are two another required fonts from Adobe : Attribute Mono & Grotesque MT. We need to subscribe to Adobe Creative Cloud service to get that fonts.

**Comment by laurengerardi** [comment]
Got it. Will ask for these 2

**Comment by laurengerardi** [comment]
Hi so with the most recent changes they sent over in Figma they removed the Strain information, they also removed the use of Attribute and Grotesque fonts.

Only Mont is now being used throughout the site (which you have access to). Let me know if there are any questions
