### ISSUE TITLE
Process - Icon Stroke Width

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#60]
Process page icon stroke widths are inconsistent.

![icon-stroke1](https://user-images.githubusercontent.com/27019705/75746921-3c605580-5d4e-11ea-86d2-4d7aa00e1427.jpg)

![icon-stroke2](https://user-images.githubusercontent.com/27019705/75746924-3d918280-5d4e-11ea-8730-f45eafbdeeb8.jpg)

**Comment by aldidas** [comment]
Updated...
