### ISSUE TITLE
FAQ Copy to add to Page

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#65]
[LRP FAQs.docx](https://github.com/laurengerardi/LiveResin/files/4282665/LRP.FAQs.docx)

**Comment by aldidas** [comment]
Updated, please check

**Comment by laurengerardi** [comment]
Looks good, for this one, can we hyperlink:

![Screen Shot 2020-03-04 at 12 19 56 PM](https://user-images.githubusercontent.com/57407119/75905224-801c9300-5e12-11ea-9ae4-52a98f3d68a5.png)

**Comment by laurengerardi** [comment]
![Screen Shot 2020-03-04 at 12 20 00 PM](https://user-images.githubusercontent.com/57407119/75905333-af330480-5e12-11ea-8ae4-0d0b2ea36181.png)

There is an extra space on second line before "vape" not sure if that's meant to be on it's own line or not?

**Comment by dickyabd** [comment]
@laurengerardi we have removed the extra space there
