### ISSUE TITLE
Navigation - State Dropdown

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#69]
They are saying it doesn't work correctly.

**Comment by dickyabd** [comment]
Hi @laurengerardi 

do you mean this sections? :
![image](https://user-images.githubusercontent.com/27019705/76816767-b3f4b100-6833-11ea-84bd-6bb57a31d5a4.png)

![image](https://user-images.githubusercontent.com/27019705/76816787-beaf4600-6833-11ea-8e39-909911041a77.png)


can you clarify, how the dropdown look like when we click the state? we don't have the guideline for that part

**Comment by laurengerardi** [comment]
Hi yes, this is only happening in safari. It should look like it does in the Age Gate drop down. 

<img width="420" alt="Screen Shot 2020-03-17 at 12 35 41 PM" src="https://user-images.githubusercontent.com/57407119/76878982-fcb86400-684b-11ea-9ffc-c961c7916f4d.png">

**Comment by laurengerardi** [comment]
Here is the updated Figma! 
https://www.figma.com/file/Jr8rxQz2auN40K3DBvu88mgg/Live-Resin-Project-Site?node-id=2597%3A2147

**Comment by aldidas** [comment]
Updated, please check

**Comment by laurengerardi** [comment]
great thanks
