### ISSUE TITLE
Most Images are Low-Res

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#7]
Noticed in the demo link; https://liveresin.ubicilembu.com/ the images are in low-res

for example :
![image](https://user-images.githubusercontent.com/27019705/74229253-9c864d80-4cf4-11ea-893c-c7fd5071fb0f.png)

![image](https://user-images.githubusercontent.com/27019705/74229294-b0ca4a80-4cf4-11ea-9405-8bf7013aeeee.png)

@laurengerardi can we ask the client to provide a separated high res image? we can not easily export the image from figma.

**Comment by laurengerardi** [comment]
Got it - will let you know what the client says.

**Comment by laurengerardi** [comment]
Hi - here is the dropbox with the assets to download. 
https://www.dropbox.com/sh/727hkb5f3bnslyh/AACj6-9DUZ1StwnQ_83VDj38a?dl=0****

**Comment by dickyabd** [comment]
not sure why the image assets still looks pixelated than in figma

**Comment by laurengerardi** [comment]
Hi, I will send this document to the design team. They were updating the Figma links. So I will ask them to call out the changes made.

**Comment by dickyabd** [comment]
@laurengerardi sorry if my comment confusing. What i mean was the image that are implemented still looks pixelated. I have checked the dropbox and the image are in hi-res. Aldi will check further in the code.

But regarding figma links, they have updated some of the ui and so many changes there especially the product page

**Comment by laurengerardi** [comment]
Can you give edit access to the document? I'm going to send to them for feedback.
