### ISSUE TITLE
Store Locator updated Figma

### ISSUE THREAD

**Issue by laurengerardi** [laurengerardi/LiveResin#70]
Here is the updated Figma! 

They have updated the Store Locator page in Figma to show the typographic treatment for State and Region.

Once more States are added in, they should be +/- (expandable/contractable) like the FAQs.

https://www.figma.com/file/Jr8rxQz2auN40K3DBvu88mgg/Live-Resin-Project-Site?node-id=2597%3A2147

**Comment by aldidas** [comment]
This is updated. Please check

**Comment by laurengerardi** [comment]
Looks great!
