### ISSUE TITLE
Overall Demo Web First Test Review

### ISSUE THREAD

**Issue by dickyabd** [laurengerardi/LiveResin#8]
Most of block height is lower than figma spec, so some of the image get more cut off than the spec and some other are out of bounds. Need to adjust more of the margins

For example :
![image](https://user-images.githubusercontent.com/27019705/74229591-4a91f780-4cf5-11ea-9af8-5371b5cca3f1.png)

![image](https://user-images.githubusercontent.com/27019705/74229532-26ceb180-4cf5-11ea-89a4-b98462107349.png)

**Comment by dickyabd** [comment]
I have tested the latest demo web, not including the product page and mobile version. Still have some UI issues, especially images that still not hi-res and some fonts style are different in implementation also i just noticed that in figma, they have several updates and some are totally different. 

Here is the test report :
https://docs.google.com/document/d/1To45c7w4WbYGmedJg_NPF5lnEI7TLDJb4ynRJOFkC1U/edit?usp=sharing

**Comment by laurengerardi** [comment]
Hi, 

So they said the Figma link has been updated to reflect the new product treatment. 

The following pages have been updated so we should look at them to update: 
-Desktop/Mobile:Homepage
-Products
-Process  

They've also updated the dropbox folder to include the video found on the Homepage and About page: https://www.dropbox.com/sh/8duscohod4m2fwl/AAD13a4kK1EmS3PG933-BGfha?dl=0

**Comment by vivachu** [comment]
@laurengerardi this is very inefficient for us to have to redo these pages and find what elements have been changed.  Can the client provide a summary of the changes?

**Comment by laurengerardi** [comment]
Yes, following up with them.

**Comment by laurengerardi** [comment]
Here is a side by side on what changed. Let me know if this all makes sense/works on your end. 
[LRP_Website Revisions_190220.pdf](https://github.com/laurengerardi/LiveResin/files/4227612/LRP_Website.Revisions_190220.pdf)
